# -*- coding: utf-8 -*-
"""RegexDJANGO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13U_RcJngAuLrHeX5pUnTg0fGBuKnUfRv
"""

#WAP to make a list of distinct elements from a list?
def unique(list1):
 
    # initialize a null list
    unique_list = []
     
    # traverse for all elements
    for x in list1:
        # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
    # print list
    for x in unique_list:
        print(x)
     
   
 
# driver code
list1 = [10, 20, 10, 30, 40, 40]
print("the unique values from 1st list is")
unique(list1)
 
 
list2 =[1, 2, 1, 1, 3, 4, 3, 3, 5]
print("\nthe unique values from 2nd list is")
unique(list2)

#Write a python program to check whether two lists are circularly identical or not?

def circularly_identical(list1, list2):
     
    return(' '.join(map(str, list2)) in ' '.join(map(str, list1 * 2)))
      
  
# driver code
list1 = [10, 10, 0, 0, 10]
list2 = [10, 10, 10, 0, 0]
list3 = [1, 10, 10, 0, 0]
  
  
# check for list 1 and list 2 
if (circularly_identical(list1, list2)):
    print("Yes")
else:
    print("No")
  
# check for list 2 and list 3 
if(circularly_identical(list2, list3)):
    print ("Yes") 
else:
    print ("No")

#Take two dictionariesand pass the to a function such that function will return a disjoint dictionary
set1 = {76.00 ,45.00, 58.00} 
set2 = {65.00 ,75.00}

  
  
#checking of disjoint of two sets
print("set1 and set2 are disjoint:", set1.isdisjoint(set2))